"""empty message

Revision ID: e61812d5a17b
Revises: b146d7aa24d3
Create Date: 2020-05-24 02:19:12.542973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61812d5a17b'
down_revision = 'b146d7aa24d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))

    op.execute('UPDATE "Venue" SET genres=ARRAY[]::text[] WHERE genres IS NULL;')

    op.alter_column('Venue', 'genres', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
